<?php /* @var $block Experius\DonationProduct\Block\Checkout\Donation\ProductList */  ?>

<div id="experius-donations">

    <?php $items = $block->getProductCollection(); ?>

    <?php  /* @var $item Magento\Catalog\Model\Product */ ?>
    <?php foreach($items as $item): ?>
        <form data-role="tocart-form" action="<?php echo $block->getAddToCartUrl($item); ?>" method="post" id="product_addtocart_form">
            <?php echo $block->getBlockHtml('formkey'); ?>
            <?php echo $item->getName(); ?>

            <input type="hidden" name="product" value="<?php echo $item->getId(); ?>">

            <input name="amount" id="amount" title="amount" class="input-text validate-number" type="text" data-validate="{required:true, 'validate-number': true}" aria-required="true" value="">

            <button type="submit" title="Add to Cart" class="action tocart primary">
                <span>Add to Cart</span>
            </button>

        </form>
    <?php endforeach; ?>

</div>

<script>


    jQuery("#product_addtocart_form").submit(function(e) {

        jQuery.ajax({
            type: "POST",
            url: jQuery("#product_addtocart_form").attr('action'),
            data: jQuery("#product_addtocart_form").serialize()
//            success: function(data)
//            {
//
//            }
        });
        e.preventDefault();
    });

</script>