<?php /* @var $block \Experius\DonationProduct\Block\Product\Type\Donation */ ?>

<div class="product-options-wrapper" id="product-options-wrapper">
    <div class="fieldset">
        <div class="field">
            <label class="label">
                <span><?php echo __('Donation Amount'); ?></span>
            </label>
            <div class="control">
                <input name="amount" id="amount" title="amount" class="input-text validate-number" type="text" data-validate="{required:true, 'validate-number': true}" aria-required="true" value="">
            </div>
        </div>
        <div class="field">
            <label class="label">
                <span><?php echo __('Donation Fixed'); ?></span>
            </label>
            <div class="control">
                <div class="options-list nested" id="options-4-list">
                    <?php foreach($block->getFixedAmounts() as $fixedAmount=>$viewFixedAmount): ?>
                    <div class="field choice admin__field admin__field-option">
                        <input type="radio" class="radio admin__control-radio" name="amount_fixed" value="<?php echo $fixedAmount; ?>">
                        <label class="label admin__field-label" for="options_4_2"><span><?php echo $viewFixedAmount; ?></span></label>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>