<fieldset class="fieldset">
    <div class="field width">
        <label class="label" for="name"><span><?php echo __('Donation Amount'); ?></span></label>
        <div class="control">
            <input name="amount" id="amount" title="amount" class="input-text validate-number" type="text" data-validate="{required:true, 'validate-number': true}" aria-required="true" value="">
        </div>
    </div>
</fieldset>