<?php /* @var $block \Experius\DonationProduct\Block\Adminhtml\Charity\Index */ ?>

<form method="GET">
    <select name="locale" class="admin__control-select" onchange="this.form.submit()">
        <?php foreach($block->getLocales() as $value=>$label): ?>
            <option value="<?php echo $value; ?>"><?php echo $label; ?></option>
        <?php endforeach; ?>
    </select>
</form>

<p style="padding: 10px; background: #f8f8f8; margin: 20px 0 0 0;">
    <?php echo __('Contribute and add your Favorite (Local) Charities to our import feed on'); ?>
    <a href="https://github.com/experius/Experius-DonationFeed" target="_blank"><?php echo __('Github'); ?></a>
</p>

<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <table class="data-grid" data-role="grid">
        <thead>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?php echo __('Image'); ?></span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?php echo __('Name'); ?></span>
            </th>
            <th class="data-grid-th">
                <span class="data-grid-cell-content"><?php echo __('Import'); ?></span>
            </th>
        </thead>
        <tbody>
            <?php foreach ($block->getCharities() as $id=>$charity) : ?>
                <tr class="data-row _odd-row">
                    <td><img src="<?php echo $charity['image_url']; ?>" width="200" height="200"/></td>
                    <td><?php echo $charity['name']; ?></td>
                    <td class="data-grid-actions-cell">
                        <a class="action-menu-item" target="_self" href="<?php echo $block->getUrl('experius_donationproduct/charity/import',['id'=>$id]); ?>"><?php echo __('Import'); ?></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
